"""
Test download with your Copernicus tokens
"""

from utils.copernicus_client import CopernicusClient

# Your tokens
ACCESS_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYVUh3VWZKaHVDVWo0X3k4ZF8xM0hxWXBYMFdwdDd2anhob2FPLUxzREZFIn0.eyJleHAiOjE3NzU5MzQwMjEsImlhdCI6MTc3NTkzMjIyMSwianRpIjoib25ydHJvOjlmNTFhZjQwLWRmZTgtYjlhZS1jZjNlLWFhMTQ4YjhjNmRlMyIsImlzcyI6Imh0dHBzOi8vaWRlbnRpdHkuZGF0YXNwYWNlLmNvcGVybmljdXMuZXUvYXV0aC9yZWFsbXMvQ0RTRSIsImF1ZCI6WyJDTE9VREZFUlJPX1BVQkxJQyIsImFjY291bnQiXSwic3ViIjoiNTFiMTc2MDUtNWE1Ny00MTExLTkxOGMtM2EwYzRmYzFjMDhmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2RzZS1wdWJsaWMiLCJzaWQiOiI4MWUxZGIyMC1lNDVlLTJiOTgtODBiOS0yNDE5NWRiMjA5NDMiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6NDIwMCIsIioiLCJodHRwczovL3dvcmtzcGFjZS5zdGFnaW5nLWNkc2UtZGF0YS1leHBsb3Jlci5hcHBzLnN0YWdpbmcuaW50cmEuY2xvdWRmZXJyby5jb20iXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImNvcGVybmljdXMtZ2VuZXJhbC1xdW90YSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLWNkYXMiLCJjb3Blcm5pY3VzLWdlbmVyYWwiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6IkFVRElFTkNFX1BVQkxJQyBvcGVuaWQgZW1haWwgcHJvZmlsZSBvbmRlbWFuZF9wcm9jZXNzaW5nIHVzZXItY29udGV4dCIsImdyb3VwX21lbWJlcnNoaXAiOlsiL2FjY2Vzc19ncm91cHMvdXNlcl90eXBvbG9neS9jb3Blcm5pY3VzX2dlbmVyYWwiLCIvb3JnYW5pemF0aW9ucy9kZWZhdWx0LTUxYjE3NjA1LTVhNTctNDExMS05MThjLTNhMGM0ZmMxYzA4Zi9yZWd1bGFyX3VzZXIiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJTbmVoYSBTaGV0dHkiLCJvcmdhbml6YXRpb25zIjpbImRlZmF1bHQtNTFiMTc2MDUtNWE1Ny00MTExLTkxOGMtM2EwYzRmYzFjMDhmIl0sInVzZXJfY29udGV4dF9pZCI6Ijc3N2NhMDhjLWY0OTUtNDM5Ni04ODkzLTNiZmI3YjU0N2JlNiIsImNvbnRleHRfcm9sZXMiOnt9LCJjb250ZXh0X2dyb3VwcyI6WyIvYWNjZXNzX2dyb3Vwcy91c2VyX3R5cG9sb2d5L2NvcGVybmljdXNfZ2VuZXJhbC8iLCIvb3JnYW5pemF0aW9ucy9kZWZhdWx0LTUxYjE3NjA1LTVhNTctNDExMS05MThjLTNhMGM0ZmMxYzA4Zi9yZWd1bGFyX3VzZXIvIl0sInByZWZlcnJlZF91c2VybmFtZSI6InNuZWhhc2hldHR5LjE4MDVAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IlNuZWhhIiwiZmFtaWx5X25hbWUiOiJTaGV0dHkiLCJ1c2VyX2NvbnRleHQiOiJkZWZhdWx0LTUxYjE3NjA1LTVhNTctNDExMS05MThjLTNhMGM0ZmMxYzA4ZiIsImVtYWlsIjoic25laGFzaGV0dHkuMTgwNUBnbWFpbC5jb20ifQ.mW_A2GGI0cNr6n7uskKTR_yugxj_YILmclSnzNJ6oeA1BcnO4nURIwV2EcmfWdifx3P3LRYDugrKRYYHJGwWpAKYhHezJon8zD4nPExncH3-WQ2O2q6A_MK--bwU6NQa-kHk-fDfKOvSwINer9nkOFcvMnvapsDiWgIitHHOZfxpGhQJMGVAAyLPTGlB3d_rE9wyGErirV5V7cBI_nMgIxzI8Zi6WonAm_BGTkjhdRhutsTwdhioQNBpdosr7Y3tlzupbvYNLwU0xWQIfoaV96paMj4A_9DCAeX0ul5HszPoPFBZPNDrpGbgdFol5eFSXQx4NDEFOmBItxHYYsUyug"
REFRESH_TOKEN = "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjODg0ZDhkYi0wNjY2LTQ5OWYtOTJkYi1hNTQwODZmMDQ5YjkifQ.eyJleHAiOjE3NzU5MzU4MjEsImlhdCI6MTc3NTkzMjIyMSwianRpIjoiYzc0ZjVkODgtY2UwZi03ZWVjLTM5MzAtMzRiNGFmMDRkMTllIiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5kYXRhc3BhY2UuY29wZXJuaWN1cy5ldS9hdXRoL3JlYWxtcy9DRFNFIiwiYXVkIjoiaHR0cHM6Ly9pZGVudGl0eS5kYXRhc3BhY2UuY29wZXJuaWN1cy5ldS9hdXRoL3JlYWxtcy9DRFNFIiwic3ViIjoiNTFiMTc2MDUtNWE1Ny00MTExLTkxOGMtM2EwYzRmYzFjMDhmIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImNkc2UtcHVibGljIiwic2lkIjoiODFlMWRiMjAtZTQ1ZS0yYjk4LTgwYjktMjQxOTVkYjIwOTQzIiwic2NvcGUiOiJBVURJRU5DRV9QVUJMSUMgYmFzaWMgd2ViLW9yaWdpbnMgb3BlbmlkIGVtYWlsIHJvbGVzIHByb2ZpbGUgb25kZW1hbmRfcHJvY2Vzc2luZyB1c2VyLWNvbnRleHQifQ.VSmDDBM4L8wuR0GUV3Vlbzt8O8ySKACvVMly3vAsnUNloyzmz46wXR_dQ64fO2sfWDSomJbFGjHQCC-Y9NefKQ"

print("=" * 80)
print("🛰️ TESTING COPERNICUS API WITH YOUR TOKENS")
print("=" * 80)

# Initialize client
client = CopernicusClient(ACCESS_TOKEN, REFRESH_TOKEN)

# Jammu & Kashmir - Srinagar area (smaller bbox for better results)
bbox = [74.7, 34.0, 75.0, 34.2]  # Srinagar/Dal Lake area

print("\n📍 Location: Srinagar, Jammu & Kashmir")
print(f"📐 BBox: {bbox}")
print("📅 Date: June 2024")
print("=" * 80)

# Search for images
results = client.search_images(
    bbox=bbox,
    start_date="2024-06-01",
    end_date="2024-06-30",
    limit=5
)

if results and results.get('features'):
    print(f"\n✅ SUCCESS! Found {len(results['features'])} images")
    
    # Download them
    client.download_images(results, "data/raw/jk_srinagar_test")
else:
    print("\n❌ No images found or search failed")
    print("\nThis could be because:")
    print("  1. Network/firewall blocking the API")
    print("  2. API endpoint temporarily down")
    print("  3. No satellite coverage for this exact area/date")
